version: '3'

services:
    # MySQL
    mysql:
        container_name: 'mysql'
        build: ./.docker/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always # コンテナが落ちたら再起動する
        tty: true
        ports:
            - '3306:3306'
        volumes:
            - ./.docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
            - ./.docker/mysql/log/mysql:/var/log/mysql # ログの保存
        networks:
            - back_bridge

networks:
    back_bridge:
        external: true
